version: "3"
services:
    app:
        build: ./app
        environment:
          - NUXT_PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ../app:/home/node/app
        tty: true
        working_dir: /home/node/app
